### ISSUE TITLE
LiquidityPools do not have the correct Asset decimals.

### ISSUE THREAD

**Issue by NickJorens** [IndigoProtocol/dexter#20]
Getting liquiditypools and then filtering them based on a their A or B asset isn't possible due to them not having the correct decimals. They're all 0.

**Comment by Sluder** [comment]
@NickJorens This is where the AssetMetadataProviders come into play. There is one provided by default, but there is a fix merged in that is not yet deployed to NPM. Ill get the latest code deployed here the next few days once I get some other fixes in

**Comment by NickJorens** [comment]
@Sluder Even with the current TokenRegistryProvider it's still not populating the correct decimals for me.
I'll wait until the fix has been merged. :)

**Comment by Sluder** [comment]
@NickJorens Please pull the new tag v1.0.5 from NPM, let me know if your issue is resolved!
